import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { ThemeToggle } from "@/components/ThemeToggle"
import { SearchForm } from "@/components/SearchForm";
import { Nav } from "@/components/Nav";
import styles from "./layout.module.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
	default: "My Blog",
	template: "%s | My Blog",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	// ページ読み込み時に即実行させる。
	const setInitialTheme = `
		(function() {
			try {
				var theme = localStrage.getItem('theme');
				if (theme) {
					document.documentElement.setAttribute('data-theme', theme);
				}
			} catch (e) {}
		})());
	`

	return (
		<html lang="ja" className={`${geistSans.variable} ${geistMono.variable}`}><head>
                {/* 
                  dangerouslySetInnerHTML を使い、
                  他の JS より先にテーマを適用させる
                */}
                <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
            </head>
			<body suppressHydrationWarning>
				<ThemeProvider>
					<header className={styles.header}>
						<p className={styles.siteTitle}>
							<a href="/">
								<Image
									src="/img_logo.webp"
									alt="OyakaWorX BLOG"
									width={150}
									height={72}
									className={styles.logo}
									priority
								/>
							</a>
						</p>
						<div className={styles.fixed}>
							<Nav />
							<SearchForm />
							<ThemeToggle />
						</div>
					</header>
					{children}
					<footer className={styles.footer}>
						<a href="/">
							<Image
								src="/img_logo-white.webp"
								alt="OyakaWorX BLOG"
								width={150}
								height={72}
								className={styles.logo}
								priority
							/>
						</a>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
